public with sharing class MyClass 
{
    String Str="";
    String Str="";
    String Str="";
    String var1="";
    String var2="";
    String Str="";
    String Str="";
    String Str="";
    String Str="";
    String Str="";
    String Str="";
    String Str="";
    String Str="";
    public static Intiger getDemo()
    {
        value= value+10;
        return value;
        add some variable;
        remove some variabale;
    }
    
}