public with sharing class MyClass 
{
    String Str="";
    String Str="";
    String Str="";
    String var1="";
    String var2="";
    String val1="";
    String val2="";
    String Str="";
    String Str="";
    String Str="";
    String val3="";
    String val 4="";
    String Str="";
    String Str="";
    String Str="";
    public static Intiger getDemo()
    {
        value= value+10;
        return value;

        add some variable;
        remove some variabale;
        adding valuees in code  ;
        removing values in code;

    }
    
}