public with sharing class MyClass 
{
    String Str="";
    String Str="";
    String Str="";
    String val1="";
    String val2="";
    String Str="";
    String Str="";
    String Str="";
    String Str="";
    String Str="";
    String variable1="";
    String variable2="";
    String Str="";
    public static Intiger getDemo()
    {
        value= value+10;
        return value;
        changes adding value ;
        changes removing value;
    }
    
}